#!/bin/csh

#************************************************
 # Author: Zachary Reed
 # Description: Project 1 csh proj1.cpp runner
 # Date: 4/15/2020
#************************************************

#number of threads:
foreach threads ( 1 2 4 8 16 32)
	foreach numTrials ( 1 10 100 1000 10000 100000 1000000)
		g++ -DNUMT=$threads -DNUMTRIALS=$numTrials proj1.cpp -o proj1 -lm -fopenmp
		./proj1
	end
end
