#!/bin/csh

#************************************************
 # Author: Zachary Reed
 # Description: Project 3 csh proj2.cpp runner
 # Date: 5/6/2020
#************************************************

#number of threads:
echo "Project 3:"
g++ proj3.cpp -o proj3 -lm -fopenmp
./proj3
